import type { FastifyInstance } from 'fastify'
import { getBoard, getCards, getCardGroupsByBoard, getCardsByGroup, getParticipants } from '../db.js'
import { getFormat } from '../../shared/formats.js'

export const ATTRIBUTION_CSV_ROW = ['Generated by', 'AnonRetro', 'https://anonretro.com?ref=export']
export const ATTRIBUTION_JSON = 'AnonRetro (https://anonretro.com?ref=export)'
export const ATTRIBUTION_MD_LINE = '*Generated by [AnonRetro](https://anonretro.com?ref=export) — free anonymous retrospective boards*'

export default async function exportRoutes(fastify: FastifyInstance) {
  fastify.get('/api/boards/:id/export.csv', async (req, reply) => {
    const data = getBoardData(req, reply)
    if (!data) return

    const { board, format, columns } = data
    const BOM = '﻿'
    const rows: string[] = [
      ['Board', board.title || board.id].map(csvEscape).join(','),
      ['Format', format.name].map(csvEscape).join(','),
      ['Exported', new Date().toISOString().slice(0, 10)].map(csvEscape).join(','),
      '',
      ['Column Name', 'Card Content', 'Total Votes', 'Author (Color Animal)', 'Group'].join(','),
    ]

    for (const col of columns) {
      let groupIndex = 1
      for (const group of col.groups) {
        const label = `Group ${groupIndex++}`
        for (const card of group.cards) {
          rows.push([col.name, card.content, card.votes, card.author, label].map(csvEscape).join(','))
        }
      }
      for (const card of col.cards) {
        rows.push([col.name, card.content, card.votes, card.author, ''].map(csvEscape).join(','))
      }
    }

    rows.push('', ATTRIBUTION_CSV_ROW.map(csvEscape).join(','))

    reply
      .header('Content-Type', 'text/csv; charset=utf-8')
      .header('Content-Disposition', `attachment; filename="retro-${board.id}.csv"`)
      .send(BOM + rows.join('\r\n'))
  })

  fastify.get('/api/boards/:id/export.json', async (req, reply) => {
    const data = getBoardData(req, reply)
    if (!data) return

    const { board, format, columns } = data

    reply
      .header('Content-Type', 'application/json')
      .header('Content-Disposition', `attachment; filename="retro-${board.id}.json"`)
      .send({
        board: {
          id: board.id,
          title: board.title || board.id,
          format: format.name,
          created_at: board.created_at,
          exported_at: new Date().toISOString(),
          generated_by: ATTRIBUTION_JSON,
        },
        columns: columns.map(col => ({
          name: col.name,
          items: [
            ...col.groups.map(g => ({ type: 'group' as const, totalVotes: g.totalVotes, cards: g.cards })),
            ...col.cards.map(c => ({ type: 'card' as const, ...c })),
          ],
        })),
      })
  })

  fastify.get('/api/boards/:id/export.md', async (req, reply) => {
    const data = getBoardData(req, reply)
    if (!data) return

    const { board, format, columns } = data
    const lines: string[] = [
      `# Retro: ${board.title || board.id}`,
      '',
      `**Format:** ${format.name}  `,
      `**Exported:** ${new Date().toISOString().slice(0, 10)}`,
      '',
      '---',
    ]

    for (const col of columns) {
      lines.push('', `## ${col.name}`, '')
      const hasContent = col.cards.length > 0 || col.groups.length > 0
      if (!hasContent) {
        lines.push('_No cards_')
        continue
      }
      const anyVotes =
        col.cards.some(c => c.votes > 0) ||
        col.groups.some(g => g.cards.some(c => c.votes > 0))
      for (const group of col.groups) {
        const groupVotes = anyVotes ? ` *(${group.totalVotes} vote${group.totalVotes !== 1 ? 's' : ''} total)*` : ''
        lines.push(`**Group**${groupVotes}`)
        for (const card of group.cards) {
          const votes = anyVotes ? ` *(${card.votes} vote${card.votes !== 1 ? 's' : ''})*` : ''
          lines.push(`  - ${card.content}${votes} — *${card.author}*`)
        }
        lines.push('')
      }
      for (const card of col.cards) {
        const votes = anyVotes ? ` *(${card.votes} vote${card.votes !== 1 ? 's' : ''})*` : ''
        lines.push(`- ${card.content}${votes} — *${card.author}*`)
      }
    }

    lines.push('', '---', ATTRIBUTION_MD_LINE)

    reply
      .header('Content-Type', 'text/markdown; charset=utf-8')
      .header('Content-Disposition', `attachment; filename="retro-${board.id}.md"`)
      .send(lines.join('\n'))
  })
}

type ExportCard = { content: string; votes: number; author: string }
type ExportGroup = { cards: ExportCard[]; totalVotes: number }
type ExportColumn = {
  name: string
  columnId: string
  cards: ExportCard[]
  groups: ExportGroup[]
}

type BoardData = {
  board: Record<string, any>
  format: ReturnType<typeof getFormat>
  columns: ExportColumn[]
}

function getBoardData(req: any, reply: any): BoardData | null {
  const { id } = req.params as { id: string }
  const adminToken = req.headers['x-admin-token'] as string | undefined

  const board = getBoard.get(id) as Record<string, any> | undefined
  if (!board) { reply.status(404).send({ error: 'Board not found.' }); return null }
  if (!adminToken || board.admin_token !== adminToken) {
    reply.status(403).send({ error: 'Admin access required.' }); return null
  }

  const format = getFormat(board.format)
  const allCards = getCards.all(id) as Record<string, any>[]
  const dbGroups = getCardGroupsByBoard.all(id) as Record<string, any>[]
  const participants = getParticipants.all(id) as Record<string, any>[]

  const identityMap = new Map<string, string>()
  for (const p of participants) {
    identityMap.set(p.participant_token, `${p.color} ${p.animal}`)
  }

  const toExportCard = (c: Record<string, any>): ExportCard => ({
    content: c.content as string,
    votes: c.votes as number,
    author: identityMap.get(c.creator_token) ?? 'Unknown',
  })

  const ungroupedCards = allCards.filter(c => !c.group_id)

  const columns = format.columns.map(col => {
    const colGroups = dbGroups
      .filter(g => g.column_id === col.id)
      .map(g => {
        const children = (getCardsByGroup.all(g.id) as Record<string, any>[]).map(toExportCard)
        return {
          cards: children,
          totalVotes: children.reduce((sum, c) => sum + c.votes, 0),
        }
      })

    return {
      name: col.label,
      columnId: col.id,
      cards: ungroupedCards
        .filter(c => c.column_id === col.id)
        .sort((a, b) => b.votes - a.votes)
        .map(toExportCard),
      groups: colGroups,
    }
  })

  return { board, format, columns }
}

export function csvEscape(value: string | number): string {
  const s = String(value)
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`
  }
  return s
}
