import { describe, it, expect } from 'vitest'
import {
  csvEscape,
  ATTRIBUTION_CSV_ROW,
  ATTRIBUTION_JSON,
  ATTRIBUTION_MD_LINE,
} from '../../src/server/routes/export.js'

describe('csvEscape', () => {
  it('returns a plain string unchanged', () => {
    expect(csvEscape('hello world')).toBe('hello world')
  })

  it('wraps a string containing a comma', () => {
    expect(csvEscape('one, two')).toBe('"one, two"')
  })

  it('wraps and escapes embedded double quotes', () => {
    expect(csvEscape('say "hi"')).toBe('"say ""hi"""')
  })

  it('wraps a string containing a newline', () => {
    expect(csvEscape('line1\nline2')).toBe('"line1\nline2"')
  })

  it('handles a number input', () => {
    expect(csvEscape(42)).toBe('42')
  })

  it('handles both comma and embedded double quote in the same string', () => {
    expect(csvEscape('"quoted", value')).toBe('"""quoted"", value"')
  })
})

describe('export attribution', () => {
  const EXPECTED_URL = 'https://anonretro.com?ref=export'

  it('CSV attribution row has the correct product and UTM URL', () => {
    expect(ATTRIBUTION_CSV_ROW[0]).toBe('Generated by')
    expect(ATTRIBUTION_CSV_ROW[1]).toBe('AnonRetro')
    expect(ATTRIBUTION_CSV_ROW[2]).toBe(EXPECTED_URL)
  })

  it('JSON generated_by contains the ref=export UTM URL', () => {
    expect(ATTRIBUTION_JSON).toContain(EXPECTED_URL)
  })

  it('Markdown footer contains the ref=export UTM URL', () => {
    expect(ATTRIBUTION_MD_LINE).toContain(EXPECTED_URL)
  })

  it('Markdown footer is a valid Markdown link', () => {
    expect(ATTRIBUTION_MD_LINE).toMatch(/\*Generated by \[AnonRetro\]\(https:\/\/[^)]+\)/)
  })
})
